import AutoGenerated from "./components/core/overview/AutoGenerated";
import CumulativePL from "./components/core/overview/CumulativePL";
import DisciplineVsPerformance from "./components/core/overview/DisciplineVsPerformance";
import Metrics from "./components/core/overview/Metrics";
import NetDailyPL from "./components/core/overview/NetDailyPL";
import Overview from "./components/core/overview/Overview";
import SessionHealth from "./components/core/overview/SessionHealth";
import SessionStatus from "./components/core/overview/SessionStatus";
import TradeDistribution from "./components/core/overview/TradeDistribution";
import TradingCalendar from "./components/core/overview/TradingCalendar";

export default function UserDashboard() {
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <div className="w-full mx-auto">
        <div className="space-y-6 sm:space-y-8">
          <SessionStatus />

          <Overview />

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 sm:gap-6">
            <CumulativePL />
            <NetDailyPL />
          </div>

          {/* Session Health & Discipline Grid - 30% / 70% on Desktop */}
          <div className="grid grid-cols-1 lg:grid-cols-[30%_69%] gap-4">
            <SessionHealth />
            <DisciplineVsPerformance />
          </div>

          <Metrics />

          <div className="grid grid-cols-1 lg:grid-cols-[30%_69%] gap-4 sm:gap-6">
            <TradeDistribution />
            <AutoGenerated />
          </div>

          <TradingCalendar />
        </div>
      </div>
    </div>
  );
}
