import { BiTime } from "react-icons/bi";
import { IoBookOutline } from "react-icons/io5";
import { TbTarget } from "react-icons/tb";

export default function AutoGenerated() {
  // This data will come from backend later
  const tasks = [
    {
      title: "Review last 2 rule-breaking trades",
      description: "You had 1 rule violation today",
      duration: "10 min",
    },
    {
      title: "Journal 1 mistake pattern (FOMO)",
      description: "FOMO appeared in your last trade",
      duration: "5 min",
    },
    {
      title: "Watch: Managing FOMO in Trading",
      description: "Linked to today's violation",
      duration: "7 min",
    },
  ];

  return (
    <div className="bg-white dark:bg-gray-800 rounded-xl lg:rounded-2xl p-5 sm:p-6 border border-gray-200 dark:border-gray-700">
      {/* Header */}
      <div className="flex items-start justify-between mb-6 sm:mb-8">
        <div className="flex justify-center items-center gap-2">
          <TbTarget className="text-orange-500 dark:text-orange-400 text-3xl sm:text-4xl" />
          <h3 className="text-lg font-bold">{"Today's"} Focus</h3>
        </div>

        <div className="bg-orange-50 dark:bg-orange-900/30 border border-orange-200 dark:border-orange-800 text-orange-600 dark:text-orange-400 px-3 py-1 rounded-lg text-xs sm:text-sm font-medium">
          Auto-generated
        </div>
      </div>

      {/* Tasks */}
      <div className="space-y-3 sm:space-y-4 mb-6">
        {tasks.map((task, index) => (
          <div
            key={index}
            className="bg-gray-50 dark:bg-gray-900/50 rounded-xl p-4 sm:p-5 border border-gray-200 dark:border-gray-700 hover:shadow-md dark:hover:shadow-gray-900/50 transition-shadow"
          >
            <div className="flex items-start justify-between gap-3">
              <div className="flex-1 min-w-0">
                <h4 className="text-sm sm:text-base font-semibold text-gray-900 dark:text-gray-100 mb-1">
                  {task.title}
                </h4>
                <p className="text-xs sm:text-sm text-gray-600 dark:text-gray-400">
                  {task.description}
                </p>
              </div>
              <div className="shrink-0 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 px-3 py-1 rounded-lg text-xs sm:text-sm text-gray-700 dark:text-gray-300 font-medium">
                {task.duration}
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Lock Countdown */}
      <div className="bg-blue-50 dark:bg-blue-950/30 border border-blue-200 dark:border-blue-900/50 rounded-xl p-4 sm:p-5 mb-4 sm:mb-6">
        <div className="flex items-start justify-between gap-3">
          <div className="flex-1">
            <h4 className="text-sm sm:text-base font-semibold text-gray-900 dark:text-gray-100 mb-1">
              Lock countdown: 2h 15m remaining
            </h4>
            <p className="text-xs sm:text-sm text-blue-700 dark:text-blue-300">
              YELLOW session cooldown
            </p>
          </div>
          <BiTime className="text-blue-600 dark:text-blue-400 text-xl sm:text-2xl shrink-0" />
        </div>
      </div>

      {/* Open Learning Hub Button */}
      <button className="w-full bg-white dark:bg-gray-900/50 border-2 border-blue-600 dark:border-blue-500 text-blue-600 dark:text-blue-400 hover:bg-blue-50 dark:hover:bg-blue-950/30 rounded-xl py-3 sm:py-4 px-4 flex items-center justify-center gap-2 font-semibold text-sm sm:text-base transition-colors">
        <IoBookOutline className="text-lg sm:text-xl" />
        <span>Open Learning Hub</span>
      </button>
    </div>
  );
}
