export const mainTheme = {
  token: {
    colorPrimary: "#f59e0b",
    colorInfo: "#f59e0b",
  },
  components: {
    Table: {
      colorTextHeading: "#DEAD35",
      colorBgContainer: "#00321F",
      colorText: "#ffffff",
      colorBorder: "#000000",
    },
    Menu: {
      colorBgContainer: "#ffffff",
      colorText: "#1183bd",
      colorItemHoverBg: "#e6f7ff",
      colorItemSelectedBg: "#2563EB",
      colorItemSelectedText: "#ffffff",
      iconSize: 24,
    },
    Button: {
      colorPrimary: "#f59e0b",
      colorTextDisabled: "#000000",
      colorPrimaryHover: "#f59e0b",
      colorPrimaryActive: "#f59e0b",
      colorBgContainerDisabled: "#ffffff",
      borderRadius: 6,
      fontSize: 14,
      controlHeight: 40,
      boxShadow: "0 0px 0 rgba(5, 145, 255, 0.1)",
    },
    Progress: {
      defaultColor: "#2563EB",
      colorSuccess: "#2563EB",
    },
    Form: {
      labelColor: "#f59e0b",
      labelFontFamily: "'Raleway', sans-serif",
      labelFontWeight: 700,
      labelFontSize: 16,
      labelLineHeight: 24,
      inputFontFamily: "'Raleway', sans-serif",
      inputFontWeight: 400,
      inputFontSize: 14,
      inputLineHeight: 20,
    },
    Input: {
      colorBorder: "#f59e0b",
      colorTextPlaceholder: "#666666",
      borderRadius: 4,
      controlHeight: 40,
    },
    InputPassword: {
      colorBorder: "#f59e0b",
      borderRadius: 4,
      controlHeight: 80,
      colorTextPlaceholder: "#666666",
    },
    InputNumber: {
      colorBorder: "#666666",
    },
    Select: {
      colorBorder: "#f59e0b",
      borderRadius: 8,
      controlHeight: 40,
      colorTextPlaceholder: "#666666",
    },
    DatePicker: {
      colorBorder: "#f59e0b",
      colorTextPlaceholder: "#000000",
      colorIcon: "#f59e0b",
      activeBg: "rgba(255, 255, 255, 0)",
    },
    Collapse: {
      colorText: "#ffffff",
      colorIcon: "#ffffff",
      headerBg: "transparent",
      colorBorder: "#ffffff",
      colorFillAlter: "transparent",
    },
    Modal: {
      colorBgContainer: "#000000",
      borderRadius: 20,
    },
    Tabs: {
      itemActiveColor: "#f59e0b",
      colorPrimary: "#f59e0b",
      colorText: "#f59e0b",
      colorTextHeading: "#f59e0b",
      colorBorderSecondary: "#f59e0b",
      itemColor: "#666666",
      itemSelectedColor: "#2563EB",
      itemHoverColor: "#2563EB",
      inkBarColor: "#2563EB",
      titleFontSize: 16,
      horizontalItemGutter: 32,
    },
    Drawer: {
      colorBgElevated: "#ffffff",
      colorText: "#000000",
      colorTextHeading: "#ffffff",
      padding: 24,
      borderRadius: 8,
    },
  },
};
